Media endpoints (/images, /audio)
luomus/laji-api pull request #2
Opened 2024-01-12 08:14 UTC by aorin

This adds /images and /audio endpoints. The logic should be the same than in the old API except some error messages have changed.

2024-01-15 09:52 UTC, olzraiti requested changes
Thanks for the effort! See the comments for change requests.

2024-01-15 09:52 UTC, olzraiti commented on src/triplestore/triplestore.service.ts
> +		return result;
The `find` method should be used only for queries that result in an array. The triplestore service has a separate `findOne` method for getting single item results. Although the functions look very similar there is the key difference that `findOne` just gets a single resource, whereas `find` uses the triplestore's `/search` endpoint which probably isn't as effective to use when querying singular resources.

2024-01-15 09:52 UTC, olzraiti commented on src/images/image.dto.ts
> +        "MZ.intellectualRightsCC-BY-NC-ND-4.0";
Swagger shows return type as `"intellectualRights": {}`, so it's not mapped correctly. I think that's because a union type like this is just removed from the compiled js. Using a string enum would probably work, but I wonder how well it will then play with `laji-schema`...

```
type IntellectualRights {
  "MZ.intellectualRightsCC-BY-SA-4.0": "MZ.intellectualRightsCC-BY-SA-4.0" ,
  ...
}
```

2024-01-17 12:12 UTC, aorin commented on src/abstract-media/abstract-media.service.ts
> +		const data: MetaUploadResponse[] = await this.mediaClient.post<any>(`api/${typeMediaNameMap[type]}`, metadata);
The `post` assumed that the type of the body is the same as the return type. I changed it so that they can be different types

2024-01-17 12:12 UTC, aorin commented on src/abstract-media/abstract-media.dto.ts
> +export type Media<T extends MediaType = any> = T extends MediaType.image ? Image : Audio;
Removed any

2024-01-17 12:12 UTC, aorin commented on .env.example
> +MEDIA_PASS=
Done

2024-01-17 12:16 UTC, aorin commented on src/abstract-media/abstract-media.service.ts
> +	}
In the `collections.service` `findOne` function can result in a `HttpException` and `getCollections` function doesn't so it's opposite with the glossary?

2024-01-17 12:16 UTC, aorin commented on src/abstract-media/abstract-media.service.ts
> +			await this.mediaClient.put<any>(`api/${typeMediaNameMap[type]}/${id}`, metadata);
Done

2024-01-17 12:20 UTC, aorin commented on src/abstract-media/abstract-media.service.ts
> +}
I converted it and tested that it works the same way than before with dates that are in ISO format

2024-01-17 12:23 UTC, aorin commented on src/collections/collections.controller.ts
> +		const ids = stringToArray(idIn);
Did this but noticed that it needs to have a filter to work correctly (`idIn.split(",").filter(id => !!id)`). Maybe it could be converted back to util later if it's used in many places

2024-01-17 12:24 UTC, aorin commented on src/guards/valid-person-token.guard.ts
> +}
Removed the guard

2024-01-17 12:27 UTC, aorin commented on src/id-utils.ts
> +export { getQName };
Yeah I guess it's not necessary as media shouldn't have any other IDs

2024-01-17 12:34 UTC, aorin commented on src/images/image.dto.ts
> +export class Image implements ImageI {
The `@Exclude() @Expose()` method seems to be the only way to whitelist properties? The `@Exclude()` means that it excludes all properties that don't have the `@Expose()` decorator. The tests didn't work with the blacklisting because the images had extra properties that were not in the schema. Could be just some test data but I thought that whitelisting is more safe

2024-01-17 12:42 UTC, aorin commented on src/interceptors/query-params/query-params.interceptor.ts
> +					context = result[0]?.["@context"];
The array can be empty (for example when searching for all images with `idIn` parameter that doesn't match anything)

2024-01-17 12:49 UTC, aorin commented on src/triplestore/triplestore.service.ts
> +		return result;
Yeah but you can't always know if there is one or more results. You can for example search images with multiple ids and if only one of the ids is valid then the result won't be an array

2024-01-17 12:53 UTC, aorin commented on src/images/image.dto.ts
> +        "MZ.intellectualRightsCC-BY-NC-ND-4.0";
I added an array for these that has the `laji-schema` type

2024-01-17 13:08 UTC, aorin commented on src/collections/collections.controller.ts
> +		const ids = stringToArray(idIn);
Actually it seems that the `idIn` can't have a default value as it disappeared from the swagger so I returned it as it was

2024-01-17 13:15 UTC, aorin commented on src/audio/audio.controller.ts
> +export class AudioController {
I changed the indentation, should be tabs now. Maybe something is wrong with eslint config

2024-01-17 15:24 UTC, olzraiti commented on src/abstract-media/abstract-media.service.ts
> +	}
I've fixed those already to the master branch

2024-01-18 10:10 UTC, olzraiti commented on src/images/image.dto.ts
> +export class Image implements ImageI {
Ah ok, thanks for the explanation. Yeah whitelisting seems to be the way here... There is a custom implementation for whitelisting in the serializer. By using it you don't need to  add typings for properties to hide/display in the model. That way you don't need to add typings for properties that are not used in the API. Now that I think about it, it might need some more work since it doesn't hide the properties from the swagger definitions.

But all of those media properties are actually used because the model is transformed (stuff is put to "media" object)... Which just seems like bad practice because now the API has to maintain this mapping model that renames many variables for no reason, instead of just automatically mapping from triplestore schema etc. But it is what it is, we'll have to inherit it...

2024-01-18 10:19 UTC, olzraiti commented on src/interceptors/query-params/query-params.interceptor.ts
> +					context = result[0]?.["@context"];
Good point. I improved the type safety for this in `master` branch - it throws an error if the context is `undefined` and  it's a query with lang param.

I think we should keep that error handling, so that we'll able to detect situations when the interceptor is used for wrong kind of data (data without context) or when there is some terrible problem in external services (data missing context).

So instead of allowing empty context for an empty array, the lang applying should be just skipped for an empty array.

But fixing this requires a merge - I can do it after this is merged.

2024-01-18 10:53 UTC, olzraiti commented on src/images/image.dto.ts
> +        "MZ.intellectualRightsCC-BY-NC-ND-4.0";
Thanks!

The DTO is quite hard to read. I think when there are multiple decorators per proeprty, it would help to have either on on their own lines:

```
    @Expose() intellectualOwner: string;

    @ApiProperty({ enum: mediaIntellectualRightsValues })
    @Expose()
    intellectualRights: ImageI["intellectualRights"];

    @Expose() keyword?: string[];

```

Noticed also that the file uses spaces instead of tabs. I'll look into what's wrong with the linter.

2024-01-18 11:41 UTC, olzraiti commented on src/collections/collections.controller.ts
> +		const ids = stringToArray(idIn);
Did some testing and I think using a transformer decorator would be the cleanest way:

```
/**
* Comma separated ids
*/
ApiProperty({ type: String, required: false })
@Transform(({ value }: { value: string }) => value.split(",").filter(id => !!id))
idIn: string[] = [];
```

This way in our internal model it's always an array, and the parsing is done in controller level.

Image controllers have to map the array to a string, because it's bypassed to the image API as it is. Which raises the question whether we should use the same `idIn` model for both media and collections.

So, either:
1. Use the transformer I showed, and the media controllers would join the array into a string
2. Media controllers don't use the same `GetPage` DTO, but their own where the `idIn` is just a simple string

2024-01-18 11:54 UTC, olzraiti commented on src/audio/audio.controller.ts
> +export class AudioController {
Eslint indent rule is broken for decorators :( We'll have to manually keep the indentation in place for properties.

https://github.com/eslint/eslint/issues/15299

2024-01-18 12:08 UTC, olzraiti commented on src/abstract-media/abstract-media.service.ts
> +}
Great, thanks!

2024-01-18 12:20 UTC, olzraiti commented on src/abstract-media/abstract-media.service.ts
> +		const data: MetaUploadResponse[] = await this.mediaClient.post<any>(`api/${typeMediaNameMap[type]}`, metadata);
Thanks, that makes sense.

How about flipping the order of `put` & `post` generic types?    Only the return type is relevant if `T` is of type `any`, `body`'s type can be inferred.

`R = T, S = T`

For example in this case it would make the usage less verbose:
```
const data = await this.mediaClient.post<MetaUploadResponse[]>(...)
```

2024-01-22 09:12 UTC, aorin commented on src/images/image.dto.ts
> +        "MZ.intellectualRightsCC-BY-NC-ND-4.0";
I added `.editorconfig` file so that the editor uses tabs automatically. I think I have also fixed all the other things in the comments

2024-01-22 11:39 UTC, olzraiti requested changes
Added a few more minor improvement wishes

2024-01-22 11:39 UTC, olzraiti commented on src/abstract-media/abstract-media.service.ts
> +	async getUploadProxy(type: MediaType, personToken: string): Promise<_request.Request> {
No reason for the underscore in `_request`. You can use the typing directly from:

```
import { Request } from "express";
```

2024-01-22 11:39 UTC, olzraiti commented on src/abstract-media/abstract-media.service.ts
> +		}
1. Unnecessary `result?.` usage - it is an array always.
2. You can avoid the `as` casting by passing the generic `T` into `findMedia`
3. Not objectively better, but in other services I've handled error throwing as eagerly as possible. This helps with type narrowing and indentation. We could do that for consistency. (This isn't strictly as important in cases like this where it doesn't affect typings and affects only very slightly to indentation, so I wouldn't have mentioned this unless there were other change requests also)

So I'd suggest the following:

```
		const [result] = await this.findMedia(type, [id]);
		if (!result) {
			throw new HttpException("Not found", 404);
		}
		return result;
```

2024-01-22 11:39 UTC, olzraiti commented on src/abstract-media/abstract-media.service.ts
> +		}
Same structure as previous:

```
		const result = await this.get(type, id);
		if (!result[urlKey]) {
			throw new HttpException("Not found", 404);
		}
		return result[urlKey] as string;

```

2024-01-22 12:40 UTC, olzraiti commented on src/abstract-media/abstract-media.service.ts
> +	async getUploadProxy(type: MediaType, personToken: string): Promise<_request.Request> {
Missed this one, then we're good to go

2024-01-22 13:00 UTC, aorin commented on src/abstract-media/abstract-media.service.ts
> +	async getUploadProxy(type: MediaType, personToken: string): Promise<_request.Request> {
I don't know why it has the underscore, the import is copied from `ProxyToOldApiService`. The type `_request.Request` is different than the express `Request`. I noticed that the `request` library is deprecated and should be replaced but that seems like a difficult task

2024-01-22 13:11 UTC, olzraiti commented on src/abstract-media/abstract-media.service.ts
> +	async getUploadProxy(type: MediaType, personToken: string): Promise<_request.Request> {
In `ProxyToOldApiService` it has the underscore because there's a variable named `request`. But yeah maybe it's ok to have it as it is now so it's not confused as easily to be some express thing instead of the deprecated lib.

2024-01-22 13:11 UTC, olzraiti commented
Good job, thanks!

2024-01-22 13:13 UTC, merged